spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lower-case-service-id: true
              enabled: true
          routes:
            - id: ms-crud
              uri: lb://ms-crud
              predicates:
                - Path=/crud/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

server:
  port: 8080
