server:
  port: 8088
spring:
  application.name: ms-ai
  ai:
    openai:
      api-key: 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
      chat:
        options:
          model: gpt-4.1

crud-base-url: http://localhost:8080/ms-crud

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
